### ISSUE TITLE
warning about undeclared variable

### ISSUE THREAD

**Issue by Xanthin** [DS-Minetest/chatbell#1]
`2017-06-08 21:12:50: WARNING[Main]: Assignment to undeclared global "f" inside a function at /home/xxx/minetest/bin/../clientmods/chatbell/init.lua:51.
`

**Comment by Desour** [comment]
Yeah, already fixed (before I saw this issue).
You are fast. :smile: 
Oh, and your real name is visible.↑

**Comment by Xanthin** [comment]
Thanks for the hint. Huh, that's what I get for fast copy/paste. :laughing:

And thanks for the mod, was exactly what I tried to achieve by modifing your "hi" mod yesterday and failed badly.
